accounts:
  - name: "jarilo"
    coins: ["20000test", "200000000aula"]
validator:
  name: "jarilo"
  staked: "100000000aula"
build:
  binary: "aula"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
