accounts:
  - name: "jarilo"
    coins: ["20000test", "200000000aula"]
validator:
  name: "jarilo"
  staked: "100000000aula"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "aula"
    mint:
      params:
        mint_denom: "aula"
    gov:
      deposit_params:
        min_deposit:
        - amount: "100000000"
          denom: "aula"
    crisis:
      constant_fee:
        amount: "1000"
        denom: "aula"
build:
  binary: "aula"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
