accounts:
  - name: "jarilo"
    coins: ["20000test", "200000000aula"]
validator:
  name: "jarilo"
  staked: "100000000aula"
genesis:
  app_state:
    accounts:
      - name: "infu1"
        address: "aula1pth9r4r2h7v5mnnexkr35djr0he4snzzqt23t2"
        coins: ["1000000000000aula","100000test"] 
      - name: "infu2"
        address: "aula1e8vnskd6rqna2fa0tcheu2ymsexkqvg95dvaad"
        coins: ["1000000000000aula","100000test"]
    staking:
      params:
        bond_denom: "aula"
    mint:
      params:
        mint_denom: "aula"
    gov:
      deposit_params:
        min_deposit:
        - amount: "100000000"
          denom: "aula"
    crisis:
      constant_fee:
        amount: "1000"
        denom: "aula"
build:
  binary: "aula"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
